apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: homelab 
  namespace: elastic
spec:
  version: 8.12.0
  nodeSets:
  - name: elastic 
    count: 4
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: nfs-k8s-keep
    config:
      node.store.allow_mmap: false
      node.roles: ["master", "data", "ingest", "transform"]
      xpack.ml.enabled: false

