apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: homelab 
  namespace: elastic
spec:
  version: 8.12.0
  nodeSets:
  - name: elastic 
    count: 4
    config:
      xpack.ml.enabled: false

