apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-release 
  namespace: loki
spec:
  targetNamespace: loki 
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 2.10.1
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: loki-cm 
---
