apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail-release 
  namespace: loki 
spec:
  targetNamespace: loki 
  chart:
    spec:
      chart: promtail 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 6.15.4
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: promtail-cm 

