# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-cm 
  namespace: loki 
data:
  values.yaml: |
    defaultVolumes:
      - name: run
        hostPath:
          path: /run/promtail
      - name: containers
        hostPath:
          path: /var/lib/containers
      - name: system 
        hostPath:
          path: /var/log/
    defaultVolumeMounts:
      - name: run
        mountPath: /run/promtail
      - name: containers
        mountPath: /var/lib/containers
        readOnly: true
      - name: system 
        mountPath: /var/log/
        readOnly: true
    config:
      enabled: true
      logLevel: info
      logFormat: logfmt
      serverPort: 3101
      clients:
        - url: http://loki-backend/loki/api/v1/push
      positions:
        filename: /run/promtail/positions.yaml
      enableTracing: false
---

