apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: meal-notifier 
  namespace: default
spec:
  schedule: "0 7 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meal-notifier
            image: rorix/meal-notifier:latest
            env:
            - name: DOPPLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cronjob-secrets
                  key: DOPPLER_TOKEN
          restartPolicy: OnFailure
---
