apiVersion: v1
kind: Secret
metadata:
    name: cronjob-secrets
    namespace: cronjobs
type: Opaque
stringData:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:D/PugrSDjKqRhmOVmUSQyjAbT7tL7wv0He3qVIWwUJ6F99qWh4v8RLe0/mqaKPBbdGJBks26PtY=,iv:WufOEpeBR9MF96G/CrQmDjfuYjc0AQKOBokEaNoi52I=,tag:yqi/yxp0pj2IPeDshtjkFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdEdrNmk1TVlmT1Q1dm53
            VW9LRDIyYk5ZaUZyZUpGWVNLWjQ3ZFR1VERRClVYQ29XY1dDdFBRWGI0L2tiWGkw
            YVpQK2k0WnFpaUxncGFFQjE4QUhJRHMKLS0tIFRYMmNsT3h1RUN1ejZqQ0VicERG
            SzJaTGdQaWNUNUR6YnBDSGw0ajkzSlEKhis69zojtQysOrYTj12+SRuoqUzvOu1S
            UkYJJZoLao3MLaKiAICWXpH4ygU2B8nmD/S+ZhBqKNhY6z02CcKTdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T03:59:47Z"
    mac: ENC[AES256_GCM,data:VUGoTfKOYEncOruedo22m/eNedICGrlrMLfUzOjh7UVosE3FOqjLu1ka3q7Y1W2VHaCdjeQ+Egq56vqTK9pBHa9RJROdQxG+38wHZxaKovNuK4S+9HfORAbj9O37SgzhhVlTKCYCDACo5+4tPaU66tZ9WGil7BrcrpRtBh0DF5c=,iv:SUXKTdOEHLf/NgWyGd0g/+vFAfo5jQ5utFsVrx+pEMk=,tag:bTW1OPkVSExnPUHkBgVUgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
