apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flaresolverr-ks

namePrefix: flaresolverr- 

resources:
- ../base

patches:
  - path: patch.yaml
    target:
      kind: Deployment 
  - path: ingress-patch.yaml
    target:
      kind: IngressRoute
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: flaresolverr-pod
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/ports/0/name
        value: flaresolverr-port
      - op: replace
        path: /spec/selector/app
        value: flaresolverr 
    target:
      kind: Service 
