apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: arr
spec:
  selector:
    matchLabels:
      app: flaresolverr 
  template:
    metadata:
      labels:
        app: flaresolverr 
    spec:
      containers:
      - name: arr-pod
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
          name: http
        volumeMounts:
        - name: config 
          mountPath: /config
      volumes:
        - name: config
          hostPath:
            path: /opt/mediaservices/prowlarr
