apiVersion: v1
kind: Secret
metadata:
    name: windmill-secret
    namespace: windmill
type: Opaque
data:
    url: ENC[AES256_GCM,data:NwT/dH4HicTFFNzPfJ/hv9/IUXMB1VT3Gd/QkM6Eo5AEq33GnOdiRUWd7ZxUAgVo84uYWimGQ8qLH/zXGotNcG/GIdTIKS3Oke21Cia4I7Jqsdz9g0wN1g==,iv:F+SUafqTNN0yJp20oqKKOQIhjNjrqxgGcjW2xf8Zkw0=,tag:IqJ2ANRcNhHAznicXdNiTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM2NjSVVZQkdaZ3BLU0dE
            cU9VTEtOSWRzZytkMVBnR3RTY2w0NFpwZFhRClVlNm9rSHVLSVRIR2k1U1N2Q0Ru
            eE0weTJ3c0ZQcDJzS0FyY3RFYmdBdHcKLS0tIFdkSTBKY1F4cFp1VldhTzdtb2hR
            dk9pYTM4OWowa2hIZ0xWcDlJZFJ5ZDgKysP2WocP48+MryMERh9Jf2sm89Bhkvom
            UV+UuueKhGipdhvfFvXEXIca2svQNpwCl9ISMuhK7QPilZJxutbbLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-11T04:45:52Z"
    mac: ENC[AES256_GCM,data:QtSYG9qC/LZsVhLE6FPRfuFPdJdScvvlJVQ0C+p3EfA4RSZqKnCHbMR2A4BVeNkNgRvyv+6PyPFfuILClJ0IXP94UJj7oWXLliBD/5ylg3DonxS7/727/E7VJbPY/btFeXQ1ucuw21on1JON73Pe21hRiLv0fUibJPPFS00L+Gk=,iv:qyOOS3anYqFRSrhb9ehWqfB+d06UyffxTWyTpYc0A7k=,tag:uEJMTkamzZAi3dkAOXQyrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
