apiVersion: v1
kind: Namespace
metadata:
  name: windmill 
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: windmill-helm
  namespace: windmill 
spec:
  interval: 10m0s
  url: https://windmill-labs.github.io/windmill-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill-release
  namespace: windmill
spec:
  targetNamespace: windmill
  chart:
    spec:
      chart: windmill 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: windmill-helm
      version: 2.0.68
  valuesFrom:
    - kind: ConfigMap
      name: windmill-cm
  interval: 5m0s
