apiVersion: v1
kind: Service
metadata:
  name: victoriametrics-svc
  namespace: metrics
spec:
  selector:
    app: victoriametrics-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428
