apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-bot
  namespace: bots
spec:
  selector:
    matchLabels:
      app: twitch-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: twitch-bot
    spec:
      containers:
        - name: twtich-bot
          image: docker.io/rorix/twitch-bot:20250617-051438@sha256:20deb02b630fe16b7fc91f2bf50d4969975c9c845751307c1e52955355002afc # {"$imagepolicy": "flux-system:bot-policy"}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: ADMIN_TOKEN
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: DISCORD_WEBHOOK
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: REDIS_URL
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: SPOTIFY_CLIENT_SECRET
            - name: SPOTIFY_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: SPOTIFY_REFRESH_TOKEN
            - name: TWITCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: TWITCH_CLIENT_ID
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: TWITCH_CLIENT_SECRET
            - name: TWITCH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bots-secrets
                  key: TWITCH_REFRESH_TOKEN
          ports:
            - name: http
              containerPort: 3000
      restartPolicy: Always
