apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-bot
  namespace: bots
spec:
  selector:
    matchLabels:
      app: twitch-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: twitch-bot
    spec:
      nodeName: eva01
      containers:
        - name: twtich-bot
          image: rorix/twitch-bot:20250617-023440 # {"$imagepolicy": "flux-system:bot-policy"}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_URL
              value: redis-svc.db:6379
            - name: DOPPLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twitch-bot-secrets
                  key: DOPPLER_TOKEN
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: twitch
              mountPath: /twitch
      restartPolicy: Always
      volumes:
        - name: twitch
          hostPath:
            path: /mnt/twitch
