apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-secrets
    namespace: bots
type: Opaque
stringData:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:K9zNYIJug7VjKVzDiW2GafmA4MF+MqKUTEHBfR660gfALTKeGCOXJrSUSBmIQg/+MU6sWALLrz0=,iv:osHQ0uDK80VMiiWinvD+IO8kkWGZqrG1/doxok6xLkU=,tag:r+BlnxUklL2ScyQMOKIyMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMlJNdmhwdWxjelhGOU81
            OXlscmpIUUFYbCtMNlZHdjBwS051dGZBSVFVClRsTStMVWRHbDR1dEQ1ZllhQXl2
            cm5UNmozMGVmQ3F5UlhyR2M3VnJzN0UKLS0tIDFOWWtoUTVjcGpNVi8xOXQwYlhz
            OGZEQTlKYXNmaDNzamdvcFhpd2JEaHMKT1ohPImcTqlinN8gvDKUBUSAwMfkoWxW
            O2U0g7gBpyg7rhjzFh7Wb6tyz5LbiExmd41UBF8z57+lELqX0b9N4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-28T03:47:02Z"
    mac: ENC[AES256_GCM,data:ZCxJ4Kc930/V8aoY8nV3Zw/1948e3f3bHbuMZJcBVpLhbrd6W2JXWc20XZxGd0d8un9hbjtRQbvtyj7t+xmMAsbRuElyduNa2uzZcUrLVXMRWnuhyZqzOVgJ4BliBlJP5kMbPygD/on98uKJ4UIC3e78mXTW7Kx+cKfNFNEeSiw=,iv:BZk4TViUJ3QMMT67M2kesjoghPrPuAeTU+zzvrBpedU=,tag:KJtDp5JrfyThvR2AJhYy/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
