apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-secrets
    namespace: bots
type: Opaque
stringData:
    DOPPLER_TOKEN: ENC[AES256_GCM,data:XvahdbSNWXvV3okkuqsYt8rJtAnYi7fG6/49vq5e3BisaLQYaMF4aSQAMWDP4fnm9hJCLIkldTU=,iv:AXFRjptMXDbehqVvPS8PzjXDkmhLlSCf11epSk3/26I=,tag:LAZYeEplJcnoQmslc53X5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ekUxOXovVWJ1ZWtPYWlq
            N1l5dG9yYXhOSVRmVkJid1luUHlsMmFrbGk0CkgrbW8wQ2JKd2ZzaEpsbG5jNXAz
            QTJjeEdQVi9xSXVZTHlQNFpTOElucjQKLS0tIGI2ZU9BT2dXZlp4UmNWM2Jtb3pi
            ZnV4L0FDVUhzWWVNRTk4ZUFJSFJXbDgK33fi9zTZQZWE9mNuGcGyeIyl2zZMXx5E
            Yw/9SGnZKiTXnHI8N8qi3OY9yHgtW4Oorqb1+75/g1qASWij5AiiOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T02:43:37Z"
    mac: ENC[AES256_GCM,data:+EBh0zbDxd4hP25biwGZHkNLEuUCBilabyFOPVn2R7xdehdbGJPNjpAwg5VqHp8MYlnfkyYdA291K5rYEXpQjZV/CBz4TwOFl9oaoFRsS84ajZeke2tRJilM4v1WEJHAN4ZWh/NJRV1iYRMsWRp2HQJPq+yigcB0xXZOWuBy2uc=,iv:LbZNlX85DiQnNUeQzlaRdPeIuXeZtRXmrCAUBr47HrQ=,tag:mNU59NjACL5YZh22VUuv6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
