apiVersion: v1
kind: Service
metadata:
  name: twitch-svc
  namespace: bots
spec:
  selector:
    app: twitch-bot
  type: ClusterIP
  ports:
  - name: twitch-bot
    protocol: TCP
    port: 80
    targetPort: 3000
---

