apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy 
  namespace: arr
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: arr-pod
        image: linuxserver/transmission
        ports:
        - containerPort: 9091
          name: http
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-pvc
