apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n
  labels:
    app: n8n-pvc
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

