apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:8EyEdA==,iv:MALVH+riKolZ8au/CAz7LgimjKmifbbhr9+s6N1+OBs=,tag:2kreS2aK4cS6PCUpEzRKJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NVA4c1dNRFljRTkzWlZt
            UFRlMjV1ak9qeC9oUml0bHJmMFZQUFkvMTFJClNTVjM4Z3ZSYWx6K0gwSkpUQTla
            em5nUzFaUmZJdlFrbE8yMEo4ZGIrUU0KLS0tIE1UakVvR2hBemI1YWkwUTdOU1NR
            bXZ5QlBtMWpIOThhbkVFdy9rQ1VGaDQKRWb+QZ163+XPVKNyNlEZh4DAzqpZ9q0l
            7JjmNHQ6sowjV7n2zAXDXWiFpUfeghU0jj83+rKBz3abqIQWAes6eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T04:22:03Z"
    mac: ENC[AES256_GCM,data:6IqIV6XCMwI/fXQkmlvHmGEQ2HhGsY1X3iWcfCgFyRcoxul7/y9sYW/IT+gMsES5qCZzHQZK1v4c69bNJ5vEANKjhhG4+eCuAMrPi9kdSbkPKcuhE+rHsY0rNgQqC10quodO3yR/HM88wveC8e3OMjrwZQa/h4viqv0PgK0D1hM=,iv:ujLBjkkozp+0R+QHGVbUqYLCPnEzH1jOYOSh5PuSDOY=,tag:pmEMtCuEd1QQTWLp2V6iyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
