apiVersion: v1
kind: Secret
metadata:
    name: shlink-secrets
    namespace: shlink
type: Opaque
data:
    db_password: ENC[AES256_GCM,data:gjxZE9Y3aYE=,iv:EqOBIW9bgysOJ4y62MQL7PUz48/vKImUQPjEjA8wzw4=,tag:aBmgj0o7bo+F5IBoeAqFVA==,type:str]
    geo_license: ENC[AES256_GCM,data:TiYp8B04pXf9zpwYaWDFCOPwo2w8KrnR,iv:qvzpXZDYWaw+QZK3zI/SHcw4HVgavptn/OmsRz9Q6Ko=,tag:H8pCPz3O8AGMhe8RJXEOUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraU8yd2FHbHRqNVJnRWl6
            YjlVVm1kZ1YvaEZCSzJaMVlxSnRpZEtLQUNzCjdTZGNyanlZdFFiTS9lT2xabjBx
            UDAxS2h1NFphZG5YSnFHRGlqdzhEVnMKLS0tIEcrNythbGZQWnhTTlA0WXhwZVk0
            QUdsd1lka01kR2lhNHRSV0dqT0JMWFEKYokccBTvjnnn//MRcyGzopreMAtB9zQa
            sz5tH01A8fUxhFJQU6EGUQQCHr9VfonO22slgdyOmJsCivDn9ARwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T03:52:09Z"
    mac: ENC[AES256_GCM,data:+kCkocNHTyMSarGvHmHZTeLMI59xNZ9RIPkANU/TRBGc0QcOzWjgvVjARvU7c4NYgnAVZZpTs9vi7ETm/IsMQ/yp+AaRhO0fkJ4tQfmaekrZ+wxkHj+o0cxHrMHAJEwxTaCYJNEl0AAMdK3YusvDJHC1GTqbVeAe7YjR1ngqMiM=,iv:5KDKfnBymQV2tuVJSaWopxZ6iBmskYsF5GVqw/O7hvU=,tag:LmnhWmWJB71rLFUWYEnYhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
