apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
    namespace: umami
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:1dTX+KWsxWNwfFq/1ANqcPCJoPHDR6cEjugL5XfAE+woGXwaKfFc/034aBpoVsLdKvqW5m8=,iv:DTAS56bgxtu8NjbJ/OrZS9zRM2cDebepOsXrqaTQhR4=,tag:vThkZK3GezPzb66WNKNWPw==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:cxhyxlV5HR4moeMbjVYCyQHiIiO1R+6+OVS/0N5JxaSM,iv:D78VVnmXOKzFggmjbSsFW1EMChUTK9GLdHgIQCcgHMk=,tag:1tOC1JnSRTJMb7Ld9ywD6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbzM2WlZVdzBuMDRkaTRV
            dnV1aUZSR1RwRGJOanYvSDJrRkFHTTBpZERZCmlQbnJiamY4SVozUTd4Y05wUGFJ
            MDgrK0ZLbXBrQVIwalZ1TXNZdTVMZzQKLS0tIHJKMi9kdUxyR2JXdzZhM0pxQVp4
            R1RwQlVWcWRaM1FqUVQweENOQTR1SU0KHrW4rqzL5FP0GLO0j8LTPpklmYkDfeiS
            HHsAljH0I+K62wA2b/gAfz5O7lRU0ktgLx/y6wXK6qgUsVf4aVgVKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T14:24:27Z"
    mac: ENC[AES256_GCM,data:/2GM872NI0pOvFq9z8Kl3GKG/bNzUOBQxOVO/De+smdlwnL8PYN2jR9F2iEiJPKW/E0KFiCnryrKwj+wqdqYivdoN/cec0qC3l6fqjUQDMFg+g3Jv6cXM+LCgoveTjTZcPBK2Hhs1ADfyXyd/Id8Ra4VBTi3u7enSREXNKnqsgg=,iv:zxOzdE8GmGSKq+tviYiqVZWM++PAgPHdekTXEdCnFbU=,tag:qyTVsST9S12FQ8oFGdW19A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
