apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr
  template:
    metadata:
      labels:
        app: arr
    spec:
      nodeName: eva02
      hostNetwork: true
      containers:
        - name: arr-pod
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          volumeMounts:
            - name: config
              mountPath: /config
      restartPolicy: Always
