apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: arr
spec:
  storageClassName: "nfs-k8s-keep"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
---
