apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: arr
spec:
  selector:
    matchLabels:
      app: radarr 
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: arr-pod
        image: linuxserver/radarr
        ports:
        - containerPort: 7878 
          name: http
        volumeMounts:
        - name: movies 
          mountPath: /movies
        - name: downloads
          mountPath: /downloads
        - name: config 
          mountPath: /config
      volumes:
        - name: movies 
          hostPath:
            path: /mnt/nas/Movies
        - name: downloads 
          hostPath:
            path: /mnt/downloads
        - name: config
          hostPath:
            path: /opt/mediaservices/radarr
