apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-cm 
  namespace: gitea 
data:
  values.yaml: |
    postgresql:
      enabled: false
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    replicaCount: 1
    strategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxSurge: "100%"
        maxUnavailable: 0
    clusterDomain: cluster.local
    image:
      repository: gitea/gitea
      pullPolicy: IfNotPresent
      rootless: true
    podSecurityContext:
      fsGroup: 1000
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: ClusterIP
        port: 22
        clusterIP: None
    persistence:
      enabled: false 
      create:  false
      mount: false 
    initContainers:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    gitea:
      admin:
        existingSecret: gitea-secrets
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      config:
        actions:
          ENABLED: true
          DEFAULT_ACTIONS_URL: github
        service:
          DISABLE_REGISTRATION: true
        server:
          DOMAIN: gitea.mvaldes.dev
          ROOT_URL: https://gitea.mvaldes.dev
          SSH_DOMAIN: giteassh.mvaldes.dev
          ENABLE_PPROF: false
        database:
          DB_TYPE: postgres
          HOST: db.bwxgdhylsmprfogstjgm.supabase.co:5432
          NAME: postgres
          USER: postgres
          PASSWD: "L@nQp^ZA6!u^cM"
          SCHEMA: gitea
      ssh:
        logLevel: "INFO"
      livenessProbe:
        enabled: true
        tcpSocket:
          port: http
        initialDelaySeconds: 200
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
      readinessProbe:
        enabled: true
        tcpSocket:
          port: http
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
    checkDeprecation: true
    test:
      enabled: true
      image:
        name: busybox
        tag: latest
---
