apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical-flux
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab-repository
  path: "./infisical"
  prune: true
  timeout: 1m
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
