# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: transmission-flux
#   namespace: flux-system
# spec:
#   interval: 10m
#   sourceRef:
#     kind: GitRepository
#     name: homelab-repository
#   path: "./arrs/transmission"
#   prune: true
#   timeout: 1m
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: windmill-flux
#   namespace: flux-system
# spec:
#   interval: 10m
#   sourceRef:
#     kind: GitRepository
#     name: homelab-repository
#   path: "./windmill"
#   prune: true
#   timeout: 1m
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: loki-flux
#   namespace: flux-system
# spec:
#   interval: 10m
#   sourceRef:
#     kind: GitRepository
#     name: homelab-repository
#   path: "./loki"
#   prune: true
#   timeout: 1m
# ---
