apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegram
  address: https://api.telegram.org
  channel: "1571728109"
  secretRef:
    name: telegram-token
