apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: telegram
  namespace: flux-system 
spec:
  summary: "Notifications"
  providerRef:
    name: telegram
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
