apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:soV+ZA==,iv:iQOU5+0KLh+87XBMUl+uSUusfIQo+VWa3nRIbQrOX/Q=,tag:FCo/m8WHIto3jroMTl0roQ==,type:str]
    client-secret: ENC[AES256_GCM,data:sl4quMyXNdVV/t+ehKH9kiNESSqj6pQy5T44aI2oSEIIWcs=,iv:sVGEGQW3FXhGFYIA+PsD5pchbkRWedqGcR8LQLvfjso=,tag:LEw7yWDwZaHk4SpSeZyYtQ==,type:str]
    client-id: ENC[AES256_GCM,data:xMNf0lqC1jDUeNkXpZC8trNnomQrouFlot+wv4DfEPoe+pMB7oZqNlIEyakL0aQf0vum+hzeWrcVe6mUEWcEhUO8SeG1U23a,iv:mHittjYMY4hC8H4wgr96bnfl/G/Z3ewVvWn0Zh7beqE=,tag:p6E8BQXeG1KVMIl90CRjFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WW9sR2d5NER2WmR1TEFt
            WVluRjZnTW5EMU5qaGIvSEFLcUJTSE9xZDN3ClljQkV6VzNqODZ6Vy9WMi84U0w4
            bEtqbSttWUxlUi9mSUI5clEzdnQzQWcKLS0tIHFSNklBSFJvT2UrWHVlOW1RVGM3
            RUI5K1lCbnYzd004Z09CSTQrUTQ1V28KnZqbo+o7u6Nq6X7niOhpJGVEXmFSQDkl
            qVpDs2mMHdUU33uwGYAnNVBApnriNGV/yf4x953uSK2UneszQ3h77A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T17:18:18Z"
    mac: ENC[AES256_GCM,data:LI8qCyVLP8qXcmysJuhxXibB7RzUt11RiMEVNdW0LZCfCy6x8U+ZtvxuYjhgrsmLz5l3b3LfN6/NTQiW4bFEsHObtiu4j6GCCP/jQ2Pvb8dX53Icsdhl4BpnlrUeaq6D3oMQAUikeR+u/8a2gnY0s6ioF1sgHDkuxj4/UElycmE=,iv:f+Fsn2ZOF5jhUJnO7Ps7lXD9EABqf1X0w93t/+S+kTE=,tag:yNwvo4TS1Q46xW8/rGS0bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
