apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:mFxbkQ==,iv:X2YcfXA8wWg3LAB/i7g+HrAm+zM6v9PYpd8gWYuknF4=,tag:zQ/4ewRQYkgpXbSlZcq4ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQTAzb3lNK2NaUUtHZFMy
            cVFXbWp2dlZ2eWpTcnBMc0FhOXBUNThOZEc0CmllVjNRZWNMaDk0U2FiaURTZUpF
            ck9mVndmWXFDNTN1SENOTVNpTkI2UUEKLS0tIDFUUmZ6STcrQitUT3ZjNUthOWpE
            OXlmMWJUQmEvYU5nQ252WjdOdHdlV0kKVkfnOob/B48GBIz127uKoh68Loq9oVU5
            pSuTB52SpYTcf8UgvNo0t5eMm+n/o2DKO1uYATvGjokiRwlGIFhxbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T19:53:40Z"
    mac: ENC[AES256_GCM,data:oU1pxGpoa9qOq01CZU/q9IbVdkj7NLfePjBuSdAAXvz364ouwCY2R8/vWFsHaN1LJ9YZZziArjjIouByxeE6AlVhDjVjvB52mxFfLEaCrnIgBY5lbrDCyHF7WBqPp3F7kHuL4DOZhvC8/vaWC9JfkCFiUG1CIcwJZcB4HAYaAIY=,iv:KsUrVxFOcNnkN8ndlSX1Zi1fZas7yh7lipahmppzNcU=,tag:Ra43dO8yTBYYcxNnMnM3IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
