# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm 
  namespace: grafana
data:
  values.yaml: |
    persistence:
      type: pvc
      enabled: true
      storageClassName: nfs-k8s-keep 
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection

    # Use an existing secret for the admin user.
    admin:
      ## Name of the secret. Can be templated.
      existingSecret: "grafana-secret"
      userKey: admin-user
      passwordKey: admin-password

    # extra plugins to install
    plugins:
      - grafana-github-datasource
      - marcusolsson-json-datasource
