apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-release 
  namespace: grafana 
spec:
  targetNamespace: grafana 
  chart:
    spec:
      chart: loki 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
      version: 5.42.0
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail-release 
  namespace: grafana 
spec:
  targetNamespace: grafana 
  chart:
    spec:
      chart: promtail 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
      version: 6.15.4
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: promtail-cm 

