# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: grafana
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:Q4fIxy8=,iv:b6HRFQT4tZX73osqZ3O0iZBhbCiHcXXBGDvF75tQ4+M=,tag:/9vsifDC3suveCHh2uz/zg==,type:str]
    admin-password: ENC[AES256_GCM,data:Pu2rhhX2288l1iY=,iv:QYeDbEyW6ZnuCHSlFKM8kZUw+tMJB/jo+HO0DBMO1UY=,tag:P9H/vLshWI7Zcl2iGMLqFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNFc4L1FnR3M4V096VTVP
            VjN1WVdGbVEyQU9FRjdaaitieVhqMzRwaTBVCk1UdVI3bWxXU1B0NjFuMXloME94
            OCsvVG94bW9URERucWpqRnJJbkFjWGcKLS0tIDFQS0VlK2V5K1JDZFFNYXg0c3Zr
            VExsOTRjRFpRUG9EdjcyYVdIS1FuaVkKTgF8FRqiWDnkXBbW9YVl8FJU1hRMizzW
            V35sbHX4BVUG1CfE9pXOiBzReIzSVcvQpJrFmF2DBUQ9Xdg+U2BUOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T21:14:44Z"
    mac: ENC[AES256_GCM,data:aRiRMpI6TJlFRSTsVbwAr6MoOwlzxf938qN+m2on15IDeZQTP+oQoUO+rhRSMZc8lzBNrIsJ8v7JyvnmTxIBVBqv9FknTA7n7dkDeVOc5Obfvj2aAfa9mcJwosVW2PLOHGv+uXqWb9YIcGmqaZ9gcPz4xsDyEtF3Hpa45joRa6k=,iv:PidsVWsX+bP9WAUfkYqH/CPE5qwe3uaj8/20qQ1yn/U=,tag:7vTfZpjDECc9YYB4tqi8Fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
