# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:qPvsqM0=,iv:79q/OqWpsJ+E/ukdj2CPsFOXCn56vSrRrdqaxYngcC4=,tag:8jpz413DbZ/+PLQCTjxyFg==,type:str]
    admin-password: ENC[AES256_GCM,data:qCOwvCVgmOkvLlIko2Q=,iv:jAYUhZjFL7UIQilP3aQodo2rhINS60kM3WK/xmJZy9g=,tag:FXv1EF1/K+6CmNrV9yNHng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWhPU2lnUDFueU5lTUFi
            Rk9DRVNYK3UyT3JHL0luZHRMeFM1M1didmhvCmF3NFZIcFFYbEJkUlM3eTVUOTdE
            Z0RpOFNtek9DU25MRmpvcXpySHNKM2sKLS0tIE9ERlh4MWh4Z3ZvOHltRVZkY0pB
            NmVvTWdMMjVZOUl1L0M0NU5tVGtwY0EKTGYzdxH7jz9PLb8SISji11UheUhfPjSh
            Oc3WaKC9bMvbkuw2wGb8CJJS/HFHArMyY9zAHRySbqvaBZBvA/1zHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T21:04:08Z"
    mac: ENC[AES256_GCM,data:Irl6IyaX22jk+j6bE9zuHzIAXoDOH20VjNu1fiY0uTytVKbb+03CLTe7q5fDjop6EcfUc5pEXnS9hIkw4meRta/I4ZbtyS3hU5CowQs9i/3FSgUVWJaWaJ98yDg3lS1IPxxs+3XQ1CVTS7wgiO/pMLanD3a7Zh+F8bOmV3J3ZvI=,iv:2Dr0Ofy76ZglayMBVsg8/UGNNpo8G7/trFMgQwbng98=,tag:wKZRu2QSNZLvVe1crhu2nA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
