# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret 
  namespace: grafana
type: Opaque
data:
  admin-user: admin
  passwordKey: v%zk^@S4!#BHLo
---
