apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets-helm
  namespace: external-secrets
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-release
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets-helm
      version: 0.17.0
  interval: 1m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
