apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-cm 
  namespace: uptime 
data:
  values.yaml: |
    image:
      registry: "registry.hub.docker"
      repository: "louislam/uptime-kuma:1"
      pullPolicy: IfNotPresent
    statefulSet:
      labels: {}
      annotations: {}
    serviceAccount:
      create: true
      annotations: {}
      name: ""
    livenessProbe:
      exec:
        command:
          - extra/healthcheck
    readinessProbe:
      httpGet:
        path: /
        port: http
        scheme: HTTP
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    persistence:
      enabled: true 
      sizeLimit: 4Gi
      storageClass: "nfs-k8s-keep"
    serviceMonitor:
      enabled: false
    testPod:
      image: docker.io/busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
      annotations: {}
    extraCertificates:
      enabled: false
      cacerts: ""
---
