apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-cm 
  namespace: uptime 
data:
  values.yaml: |
    image:
      repository: louislam/uptime-kuma
      pullPolicy: IfNotPresent
    useDeploy: true 
    serviceAccount:
      create: false
    podEnv:
      - name: "UPTIME_KUMA_PORT"
        value: "3001"
    service:
      type: ClusterIP
      port: 3001
    ingress:
      enabled: false
    livenessProbe:
      enabled: true
      timeoutSeconds: 2
      initialDelaySeconds: 15
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
    volume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClassName: "nfs-k8s"
    strategy:
      type: Recreate
    serviceMonitor:
      enabled: false
    dnsPolicy: ""
---
