apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-cm 
  namespace: infisical 
data:
  values.yaml: |
    nameOverride: "infisical"
    fullnameOverride: "infisical"

    infisical:
      enabled: true
      name: infisical
      autoDatabaseSchemaMigration: true
      fullnameOverride: ""
      podAnnotations: {}
      deploymentAnnotations: {}
      replicaCount: 6

      image:
        repository: infisical/infisical
        tag: "v0.131.0-postgres"
        pullPolicy: IfNotPresent

      kubeSecretRef: "infisical-secrets"
      service:
        type: ClusterIP

      resources:
        limits:
          memory: 210Mi
        requests:
          cpu: 200m

    ingress:
      enabled: false 

    postgresql:
      enabled: false 

    redis:
      enabled: false 
