apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-cm 
  namespace: infisical 
data:
  values.yaml: |
    infisical:
      enabled: true
      name: infisical

      autoDatabaseSchemaMigration: false
      databaseSchemaMigrationJob:
        image:
          repository: ghcr.io/groundnuty/k8s-wait-for
          tag: no-root-v2.0
          pullPolicy: IfNotPresent

      serviceAccount:
        create: true
        name: infisical-sa 

      replicaCount: 1

      image:
        repository: infisical/infisical
        tag: "v0.131.0-postgres"
        pullPolicy: IfNotPresent
        imagePullSecrets: []

      kubeSecretRef: "infisical-secrets"

      service:
        type: ClusterIP

      resources:
        limits:
          memory: 600Mi
        requests:
          cpu: 350m

    ingress:
      enabled: false 

    postgresql:
      enabled: false 
      useExistingPostgresSecret:
        enabled: true 
        existingConnectionStringSecret:
          name: "infisical-secrets"
          key: "DB_CONNECTION_URI"

    redis:
      enabled: false
