apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical-helm 
  namespace: infisical 
spec:
  interval: 10m0s
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-release
  namespace: infisical 
spec:
  targetNamespace: infisical 
  chart:
    spec:
      chart: infisical
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: infisical-helm
      version: 0.4.2
  valuesFrom:
    - kind: ConfigMap
      name: infisical-cm 
  interval: 5m0s
