apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-repository
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/mvaldes14/k8s-apps
