apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |-
    tunnel: daf39100-197b-4d41-9bfd-a0b28e309d03
    credentials-file: /etc/cloudflared/creds/tunnel.json
    metrics: 0.0.0.0:2000
    no-autoupdate: false
    ingress:
    - hostname: atlantis.mvaldes.dev
      service: http://atlantis-atlantis-release.atlantis:80
    - hostname: uptime.mvaldes.dev
      service: http://uptime-svc.uptime:80
    - hostname: draw.mvaldes.dev
      service: http://excalidraw-service.excalidraw:80
    - hostname: links.mvaldes.dev
      service: http://shlink-svc-api.shlink:80
    - hostname: windmill.mvaldes.dev
      service: http://windmill-app.windmill:8000
    - hostname: grafana.mvaldes.dev
      service: http://grafana-grafana-release.grafana
    - hostname: umami.mvaldes.dev
      service: http://umami-svc.umami
    - hostname: kibana.mvaldes.dev
      service: https://kibana-kb-http.elastic:5601
      originRequest:
        noTLSVerify: true
    - hostname: elastic.mvaldes.dev
      service: https://homelab-es-http.elastic:9200
      originRequest:
        noTLSVerify: true
    - hostname: bots.mvaldes.dev
      service: http://twitch-svc.bots
    - hostname: hoa.mvaldes.dev
      service: http://hoa-svc.hoa
    - hostname: docs.mvaldes.dev
      service: http://paperless-svc.paperless
    - hostname: search.mvaldes.dev
      service: http://search-svc.search
    - service: http_status:404
