apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |-
    tunnel: daf39100-197b-4d41-9bfd-a0b28e309d03
    credentials-file: /etc/cloudflared/creds/tunnel.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: k8s.mvaldes.dev
      service: http://nginx-service.default:80
    - hostname: atlantis.mvaldes.dev
      service: http://atlantis-atlantis-release.atlantis:80
    - hostname: wiki.mvaldes.dev
      service: http://wiki-wiki-release.wiki:80
    - hostname: uptime.mvaldes.dev
      service: http://uptime-uptime-release-uptime-kuma.uptime:80
    - hostname: draw.mvaldes.dev
      service: http://excalidraw-service.excalidraw:80
    - hostname: links.mvaldes.dev
      service: http://shlink-svc-api.shlink:80
    - service: http_status:404
