apiVersion: v1
kind: Service
metadata:
  name: cloudflared-svc
  namespace: cloudflared 
spec:
  selector:
    app: cloudflared
  ports:
  - name: cloudflared-service
    port: 80
    targetPort: 2000
---

