apiVersion: v1
kind: Service
metadata:
  name: cloudflared-svc
  namespace: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      name: cloudflared-monitor
      targetPort: 2000
