apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  storageClassName: "nfs-k8s-keep"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
