apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: db
type: Opaque
data:
    db_password: ENC[AES256_GCM,data:3z+kZ8qE8yk=,iv:C9sgskl3oZiVQufNaaBIxste28byWu5Qo9sPSnaHBN8=,tag:ocdPYFgpxU48NemNYWIvLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MUFjOStDc292ZmwvTDcy
            U1FkcTdnWlQvVVR5S3haYjhwTElicGdVZGw4CkJoRTExSWU3REV2ZVNzekNmaHpp
            aWhTRDF1bjh6YVoyUzZ1N1JseUFIMDQKLS0tIEhXaDZCVEhmRHhhSW4yMFdBTmlz
            Sm10RjlEcW9nKzVTQVlwNUJDaGJTV1EKmjjPctqk3ij31ViVminWMBVr/B8xtf8I
            uzoMRv/+gIAU7FtOs77VlS8j8sw/NUqs3STxskT4dH/xK11Ws5Xeuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T18:24:33Z"
    mac: ENC[AES256_GCM,data:83JoArrsxXgFjmgsSetTD0N+2UJYFlkZ2u0f6iqATiqaPmsPEgPU7R/2o308PmWG5hp3kGpV9qzaE7M+oBR213mW8oKHVyGlHjGywK1K7Z6A+tgpP/H8OhlQ2FNKnE0ndt05V2Dur7oHcUgsK3vPCE5rVL+xvSG+Ga3jl6e8TqQ=,iv:OJjFj9hqwRfGccP30E8UvUmm7f4AjeyfvOI5qxP55Lo=,tag:Swna/a8u1L2kUvvjxiWgiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
