apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: db
type: Opaque
data:
    db_password: ENC[AES256_GCM,data:2BV/qOwwbME=,iv:amVjiRvItrwF3TLK1Is5HUQ8ZsgAz/uXZUgmDnvmxyw=,tag:Lw+a3Ebi7yHHPjGoyq+9rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXU4a0lqaXR0aWRHRURR
            c0JuZHZvRW8rVFZyOGFjUkI5d1Jab2ZLQ1NJCmx1UEp2VmdjSlZLUGx4Nk4vOXQw
            SHlnVTRyd1FCWUFBYkNjSmlTYjdXNlkKLS0tIDI1UjRxYm1MSkEvY0xEa25WajBS
            MTNZTzlzSVdmWGlrNVRhVDIvcWIrY1UKCzL9ooRUP/GVcOoBhYAYxrMB6PO3LckE
            csGoYDPMRglKC65uCO2aDe5Zdn5t4BYH+okf2JRuDOZlmFh+iQyMKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T05:02:40Z"
    mac: ENC[AES256_GCM,data:ByjU3TYMr0AfPtUmnESLuoauQvakB5pzw9KDVKz9h+1zbpym+oBROhWzVjI5FLepGw44HoMhhfeWDew5XTULYpAEe8bbOBeGxmt7HHKQ0RqpHRr0DlVMzcItslvzVajg6OaYLGXWb14jbkcnYiS/4b0nQGhHvm+EnfP828zW3XI=,iv:5MQa/Cw+lN5VZ0Fr+/IYbiaAdrNGViRn7QC6gD3miwY=,tag:+894QjEJRm3wBoRJ7L0fwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
