apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: db
type: Opaque
data:
    db_password: ENC[AES256_GCM,data:RElGV6PTdCw=,iv:RRtW/V8cgEurcPLsLu6L60sfl36hbCgOjpM9lbMn9cc=,tag:DDkp4bmpdGPE9IfEVKMZjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla0xzaVdwblk2UVh0NSsr
            MU9GTG9Kakg2REg4QTdSZVgvN1dpMFlQNWljCi9mR0xLZVpWVmxGem1xNEZHR3FY
            ZVpwSFd3bGhVKzArdFlxUGFYMlhQNWsKLS0tIEdXRTVCVXBhd0U1K2w1R2ZBTFBm
            ZXBrZlNWZEp4OUU2TEw4WS9ib3MxRFUK+5TDDq+p4ixBNKeJjFt0eqPMQlzPJ4f/
            zIHE1KHthKM6RAPs3mvLmVUpkio7z59BAFPZ2ocbL6xoFwVAU2cmYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T19:43:32Z"
    mac: ENC[AES256_GCM,data:0R5EcXJFFh6/fjF2a3tMyLjr+0BWwjTjfagwvKBzhy+winZ375MramgVH279ZIwRkMa9BRruhTfzRYak/qj1P5KmXwHxfl40BUhtZ/DFOaQlBAKq9STd98u03tHuNlDgOh3yxlQcMULlDH70HVuR47qTX90QtE1Bv4k1XFLAJTo=,iv:R/ZHakg6F38bfGrIIFyDXVw1B2bEnq1ymg6x0nKn9gU=,tag:7iX1s47brreC0JLnnM4TSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
