apiVersion: v1
kind: Secret
metadata:
    name: vault-token
    namespace: vault
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GewvvuuFyHUUufwyc1J+sN/NZB1xqrxpjq9BwC0kck3Nmfkny92aWTWcLpxRWbXvqEwzB94skhCwbAYE0XZbZoLMzxWQ+GjGRa/8ZJsa3zKRTvNGierluTWBOoeBCHbg6b7L1CGq8xh+TZ6+TU3Msvl4PpvU+mH8ZTuP/5Sb5m7R9g12/hJLY1d0s5YcCrtdt/4UkaRK3Bon19JT1hUpVxAyIunRMrjnpb82ZvNEP4XAXKua4qRJ+T7vTOIWedZsuZjUzdlkxiupZTXb10TcsRKjFqXNpGt5gmsrncK4GnWkHJX3WS4Ev09geVwOUlSWrIxygDBjsfwy1OKapOds5Ko6bke1HJatcrSkgoPmHDbjilDjj3lDs/59ajX5kM6bf9IoNgvtN9cauvwVZIOi+x08fwhr6iPdg6pNw8SdG3D0vbh5fkgOj/h44yvs/XsfnixoAXdaoYVrkqIMxI4co+7ceZWq3RHjJFdliiwkaWhkNpSl/5LzvvVbkePe+LeIsyUmcyaQxXRLdAy9L2xTyzbWZJbg1aZI0G6+n1NfX555cQ3OBdyuW3JK6T37yXx5mK91oYw27VsAVSa70u5ahyGeXtgbjzhWKf6qWPJm64UmzV8WOerrf2iCXal1/jWVk1h1dAFf4MW+0d95jp/Ir6dCcFPTTNZR1zHGscFlxzNNCExsmgtUj4LuhofY+qKomybBKkxBW5rhkyvDqFKCTRXMPbPu47EFS8L/jE8LKHE1W50DaVXi1Rrn7k5wLzLNyw8OVGu0pXgeDrzRjcbJGT6I/hA+ubuUzyQhvbVQajMzqrkTaXZOGUbCaweIB9TWim/hWmp6xpj0rCZ5z2TWCXm/01a440X9zfCJPdmfivMGMnQDU7s/5ealFSDr8jaNvK6G75pyDDab9Mw3OKcngkjomoFzVlEooeKLQePP432eFWIaId3+SKHlTiOddZsZoe4RMjPepC2nhlQLQ8JiK7am6D+sPWO3c77tnewT7LhGEWsKiQ4jw/owx3m1PpwxPcbSdTfrkLfoXI+1HsaDh+5taDHCx/Ct/PiOt0Ylyt3AVXgkGQe8NHWw9fv/JuW1TJVOHM8zWYDhrtt8kFjZI0fFykbghDnr/01Hq6OjsohfpAsWOVFfSxFXbtvfJzWVZ1zCriXtpP5x5imEV0y3uiiBT8dUIuVPJej0Okgx9xRoZBrEmNdF1zbie6gOaA==,iv:lSyWVbUQ+JBDZzpq/4hTKpUf2LL223cN12rqXMAk2Ng=,tag:9k+yrwca9qQGHX09oMFPGA==,type:str]
sops:
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VWN5eFc1UFZTYWluR2FZ
            Qi9jS2J6YTJPdWo3NkovUWhuQVh3YjFoaFRnClRYVnNBUHZmSEJmSDdHTTNFZVBG
            MzRWVmZrZml5c0Ezc2NXZ1hNQWlISHcKLS0tIC9MODVNR2tRSE42U01GNVE3Q2to
            TUJkbmpLNGttcnBuRTB3WXVMN0h1ZVEKsncRt/lD7ZpBI75qqGQ6+cDtlo6r6F/q
            2oCbgpqA1jQzkCnJzXZyEkz7WdroNiLsF+iGor0e30RcLeGIG3Ubeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T04:12:36Z"
    mac: ENC[AES256_GCM,data:RmT+e9rF7ZlFxfChgRS3Dwks84H2tB4+xrZkbIQs6jkeyOJbPvTgkdR0pB8Ol1gO2sSLQaZX2mKVQh6n0JqzKC1K3dz4455sP1tpjf+9yy+ujXEKZmb6A3nDyuQnvB7CUtHZ22cR/RYFdz6aq9o7B29TPCMoMzevmgCCnT7NIsY=,iv:fdQoe8yap+nKTCKT2yoVnQqV9Kjcs0AnSZA7L0ODmjI=,tag:jrq03wiCZ76lp9nthucuJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
