apiVersion: v1
kind: Namespace
metadata:
  name: vault 
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault-helm
  namespace: vault 
spec:
  interval: 1m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-release
  namespace: vault 
spec:
  targetNamespace: vault 
  chart:
    spec:
      chart: vault 
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault-helm
      version: 0.30.0 
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: vault-cm
