apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logs
data:
  agent.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
      internal_logs:
        type: internal_logs
    transforms:
      filter_vector:
        type: filter
        inputs: [kubernetes_logs]
        condition: .kubernetes.container_name != "vector-agent"
      parser:
        type: remap
        inputs: [filter_vector]
        source: |
          .log = parse_json(.message) ?? .message
    sinks:
      victorialogs:
        type: elasticsearch
        endpoints:
        - http://victorialogs-svc.logs:9428/insert/elasticsearch/
        healthcheck:
          enabled: false
        inputs:
        - parser
        api_version: v8
        mode: bulk
        compression: gzip
        request:
          headers:
            VL-Msg-Field: log
            VL-Time-Field: timestamp
            VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name
