apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argo.mvaldes.dev`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
