apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: arr
spec:
  selector:
    matchLabels:
      app: readarr 
  template:
    metadata:
      labels:
        app: readarr
    spec:
      containers:
      - name: arr-pod
        image: ghcr.io/hotio/readarr
        ports:
        - containerPort: 8787
          name: http
        volumeMounts:
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: readarr-pvc
      - name: downloads 
        hostPath:
          path: /mnt/downloads
---
