apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store-apps
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "https://vault.mvaldes.dev"
      path: "apps"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-service-role"
          serviceAccountRef:
            name: "v-root-vault-se-1750179687-zz6hib83gezxsbqvbee076ci"
          secretRef:
            name: "vault-token"
            namespace: "vault"
            key: "bot-token"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store-core
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault: 
      server: "https://vault.mvaldes.dev"
      path: "core"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-service-role"
          serviceAccountRef:
            name: "v-root-vault-se-1750179687-zz6hib83gezxsbqvbee076ci"
          secretRef:
            name: "vault-token"
            namespace: "vault"
            key: "bot-token"
