apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio
  name: minio-deploy
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio-pod
        image: docker.io/bitnami/minio:2022
        ports:
        - containerPort: 9000
        - containerPort: 9001
        imagePullPolicy: Always
        env:
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "https://s3.mvaldes.dev.com/minio/"
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "adminadmin"
        - name: MINIO_DEFAULT_BUCKETS
          value: "images"
        volumeMounts:
        - name: minio-storage
          mountPath: "/data"
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
