apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc 
  namespace: minio
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

