apiVersion: v1
kind: Service
metadata:
  name: minio-svc 
  namespace: minio 
spec:
  selector:
    app:  minio
  type: ClusterIP
  ports: 
  - protocol: TCP
    port: 9000 
    targetPort: 9000 
  - protocol: TCP
    port: 9001 
    targetPort: 9001

