apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-pvc 
  namespace: nocodb 
spec:
  storageClassName: nfs-k8s-keep
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
