apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |-
    pages:
    - name: Home
      columns:
        - size: small
          widgets:
            - type: weather
              units: metric
              location: Minneapolis, United States 
            - type: twitch-channels
              channels:
                - theprimeagen
                - thealf4stream
                - teej_dv
                - thedojomx
                - typecraft
                - gentleman_programming

        - size: full
          widgets:
            - type: hacker-news

            - type: videos
              channels:
                - UClFSU9_bUb4Rc6OYfTt5SPw # PDS
                - UCMAMBNg2JIJznIWATvDXiKg # DOJOMX
                - UCsBjURrPoezykLs9EqgamOA # Fireship
                - UCWQaM7SpSECp9FELz-cHzuQ # DreamsofCode
                - UCd3dNckv1Za2coSaHGHl5aA # TJDV

            - type: reddit
              subreddit: selfhosted

    - name: RSS
      columns:
        - size: full
          widgets:
            - type: rss
              limit: 20
              collapse-after: 3
              cache: 3h
              feeds:
                - url: https://ciechanow.ski/atom.xml
                - url: https://www.joshwcomeau.com/rss.xml
                  title: Josh Comeau
                - url: https://samwho.dev/rss.xml
                - url: https://awesomekling.github.io/feed.xml
                - url: https://ishadeed.com/feed.xml
                  title: Ahmad Shadeed
