apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance-deploy
  namespace: glance
  labels:
    app: glance-deploy
spec:
  selector:
    matchLabels:
      app: glance-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: glance-deploy
    spec:
      containers:
        - name: glance-deploy
          image: glanceapp/glance
          livenessProbe:
            tcpSocket:
              port: 8080
          volumeMounts:
            - name: glance-config
              mountPath: /app/glance.yml
              subPath: glance.yml
          ports:
            - containerPort: 8080
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
            items:
              - key: glance.yml
                path: glance.yml
      restartPolicy: Always
