apiVersion: v1
kind: Service
metadata:
  name: glance-svc
  namespace: glance
spec:
  selector:
    app: glance-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
