# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-pvc
  namespace: search
  labels:
    app: search-pvc
spec:
  storageClassName: nfs-k8s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
