apiVersion: v1
kind: Service
metadata:
  name: search-svc 
  namespace: search 
spec:
  selector:
    app: search-deploy
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

