apiVersion: v1
kind: Secret
metadata:
    name: atlantis-tokens
    namespace: atlantis
type: Opaque
stringData:
    tfe-token: ENC[AES256_GCM,data:X8hSLfK9hzfssLGZqLwkjAosElcpr0vzU7EsAldQ2qdGuIdHGU0oW30JXZUUy77ZxW2MHc2Gw6Mkt85Bd/aQBdUzSxox5qBJsy1ZDWnX92gSFVVW0h8p001m,iv:+1+omkp8LIszu/GCvGdqVH3IZMcYSHwLeekLlc1R//s=,tag:GMAa2V7wMgxbeIFgo/KeHw==,type:str]
    gh-user: ENC[AES256_GCM,data:jdxpHXDbGvet,iv:+p31xfBEOf9iVohVADB1pteaJanPuz5Q850YpnrKETk=,tag:9ILPTcjFgDWrUdUqs2XWGA==,type:str]
    gh-token: ENC[AES256_GCM,data:wT/7+sIpWDBjY/7DYSNuvu9fbZir4KcCkDNX2nEEYmYMRFv7/zLE/8xIROenjDB4i46sHqjpwUL2tjGkZsololAs9HYZxFBNGY2xx0dSEsJhk/zb7agEmiOUigJM,iv:BPfjs21yr7i3xuuA1x7XPWLCuaAlic0Lmt/BBM9Tzjs=,tag:VSic0kuZTltsbeFzSbrJsw==,type:str]
    gh-webhook-secret: ENC[AES256_GCM,data:mCAS75a8q7yavww=,iv:PvTcZcqgGj0lPsWbidBpAqfKVOgWoSZMclupdipxIxE=,tag:gJQXtVNrUR772d0b6y5IOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeXIyUDJMMFlacjhOdC83
            aFVGd3dFd1pBQjZQWGg4K0VmVE0zVjY0Mm5VCi9JdTZhMWp2QVpWUTZ3bXRqZkdY
            ZXpnbHNEZDhUTnZ3SGtEdDBPVnU2bTAKLS0tIG5vYTduTmtLVHJRQ1FQblB1QXpw
            U2RyNzAzQjhQQnhwdlMxRU5FcGpoMGcKwn5xR7WrUg81vcYvXPw5bZh/6MArYhJh
            c+Hof8z465FtyZhjZCZr7ubCBQJkfwkXM4xf+lyX8nwcNzPp8IB0Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T20:57:06Z"
    mac: ENC[AES256_GCM,data:Ryaz03fIT0p6JEAfMdVh61NBucBUbE9iVf80f9R8o8iG5ODcHGgUMBrxrKUKTHPuN61gVSVuRXHsweuBBt5oEfJ/xSEvKLxVzMpYcDUSekO5c2CoY7IuRxOfOtZhQVXdywNkzgKpWL8VfkPO2MoD1i5kMVjTW7H1N/i/rdHxxtM=,iv:JraTb2HV7Iz8pDIFqqPJqW38tFuX6M/TdHtdmCmALcs=,tag:V8barhA7lh7+RxPknmJsyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
