apiVersion: v1
kind: Secret
metadata:
    name: atlantis-tokens
    namespace: atlantis
type: Opaque
stringData:
    tfe-token: ENC[AES256_GCM,data:SLdi2dp//iexUVh99kxefzXtSFT8YmoYJTn0koh5KIkihQeluBrrqhPkxXSTx5LLNPVZJlTWXs2Gcb6J5yk5S5F8gYav3sBUlu9CJ3Q+pXYDWspipQVhJntl,iv:VuHdGpj8CVo3OjdP2DAABp8R7z5/olIDe2NetWYg6DY=,tag:98A4ThOoLYfkBLA3UZkaHQ==,type:str]
    gh-user: ENC[AES256_GCM,data:Ho13VzQ9IggS,iv:JjU+cn6zCXgg5Tr7bnrGQvpET1nz5EOB+gdP+v7cXg8=,tag:aUMzHzPoQxQcasIXEJ2NNQ==,type:str]
    gh-token: ENC[AES256_GCM,data:0h2hRSD1XiWDy30ZQF119D1krZsmYkUbTRlQUu1PMyFZqBx2bfu6VA==,iv:noMrUvC6r3iUkJRppBmePCSieQDxqOUrCJTLMPJ3ov0=,tag:ev7RIdq/8hAFhjz5w3uqyw==,type:str]
    gh-webhook-secret: ENC[AES256_GCM,data:A5Ijj/5b0GDOHMo=,iv:vQCPmdLpxL6iTcIVW6RJ/3LTcO98AYKu2CrrnV8AJAI=,tag:KXNZfhUyGOXpBzRzpuN8Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1emykjszgesgtwyth9jkc3x24zuzpfvrkxcwzk6lcsc0ecv66defss5ncp0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WVJYNWRwYnlUc3FiWit2
            RFFmR2FKMldxV2JTOXBKUlJQRlZrVDhld3lNClZWcnpMUlZBcG53b2R0aFBYTWVT
            ajBKQ3FzU1dMdnFOODVxazViTHdCeGsKLS0tIFB0TnJTMXJsUHk4OWpKTXF4dGwv
            dlU1YVVaWEFXaE9HejUyQnlrVmFzMlkKICVh36BeU3qzzS52HJuTR7pPR5l7d2m3
            8YyoaokgGGCcvP89EF5cvhNekzTgcD+D0KpYMMZ2veZD8N88Yeo8uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:43:34Z"
    mac: ENC[AES256_GCM,data:gs4M0GlwfvXZc78BVQB8U2bv3K5MD18yscpEw2xm0TmqybfWen69JxJeFbfgcJdmyGrCq3SNNzGdmLhTm/QEvTkjL+irJOVSNQkfG3CIrzRvx9UAVKSnT+x2Ho7d3Yxa3hGXAil63BkN3tJFNjZ4eQ4n7fujPLz6Nd92bet3wWc=,iv:rrBmw+xB+sEg2rvmIdmI9J6q9GqChr7omo+84tIxB4U=,tag:72DFAjxmwSPFsaJCRxvisQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
