apiVersion: v1
kind: Secret
metadata:
    name: atlantis-tokens
    namespace: atlantis
type: Opaque
data:
    tfe-token: ENC[AES256_GCM,data:YF5SJNmme6xF4gYE9OSjPXSNSSh5+HnWDDFdnsC3JcisBqQLWznFiSYZu/aCDMKE62KCeuzd1+TfFnb+f3HqUpXk0WSNyqmN6YSye7lN1+wXKVXxbhb2/bZPCDh/zVIKEmI7/hJ9CJZ84IcYA8gdRGsbIcQlgrdO,iv:Q/1wtIhpGPpVM3zKwntgTlbhNNJ6FrYqSZGDIrT5zXs=,tag:jCuyU9Xt+bBn6mQEphM3Wg==,type:str]
    gh-user: ENC[AES256_GCM,data:Yo7qmCTmnJb//QRY,iv:66s87zMJcRrM86LUhcuQnKf8DHGBgUtvw5HrcHZY3hc=,tag:glPoIbxlNwxm7dhQwZFoQA==,type:str]
    gh-token: ENC[AES256_GCM,data:0vZF1+YfAd8DPOqTaDV/f8d2/hFjw3Gd6sYXJljxybfbtvrOmm/YDT2/5Oy3Tq1Nsx+MT2GJrp44ObSPpz1htuoqtBbxKUlHNBgxRGJ2oJS+ghGAig8YDnpT4X0TV63HjmzYlz/+aYcmc3d1UWm8UAWQzyArzx1nWVEVrg==,iv:m85x1i78P2X656MZYsQaZf58cNFmYUqWaaWXb+kNJYA=,tag:BXFTsEAGT+iaCi3PDoNVEA==,type:str]
    gh-webhook-secret: ENC[AES256_GCM,data:fQGNoeJ0YMC2OyQc6wh+dWPY8hMmKwa4fWTRq/29B/CIa1cUFl/mqo0n7bO2RjHJMHyKwMMeigcoNU8O/kyq+RTIew7APw3kzxUrbEg1f4laROvc9CyAlIHwoWdNJ3bq7OFjKhGyIPG+rCrFR9GyzcAowOOpf5h24ranYw==,iv:nGuAA3BMzaF2zjIgPWNcSbh+u5kaR5BGX7UD+5+7DbA=,tag:UbcCajHwI1ay6G8EEmdf/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u50tag47wnmuxsspneyd3cs8vrnk4pqzwq99aat29rluqdev5cls2yzjgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXlRNnNhMjJ3T0RKOHVP
            NVcvNkZ1V1gxOWlKU2Z2cVE1bEFjSm0yL3hZCnN2Vm9ieEFYMzlPaUZNck9INFhS
            cE50R2ZZQ3BxQVl0c1JoTnppaFEvbGsKLS0tIHNMTWIyMzZ5dFdUTDNUbUZRV2I0
            L2NlU3VJZjBUa0NySWlORjdrbUsxODAKCaMDpK+jpWwfrRjRgWdxQr6CdB69YiQG
            41mpbMRFXH/DWa1vEMTL4S3yWSBsw2jK6oW+1zvKePqhBglxGkcCSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T04:40:35Z"
    mac: ENC[AES256_GCM,data:ZXFM3fu8PQO3AfsMXkFyCWuL6UL6Jzkfyz7lvs1QK5YSTSl3k03Sv6mDsujU8pkr2WOJJcXGSUjcAAeHvJV9W4eLVpd+amWegLR0+ZblADoTz5nBJNPmIXPLfFpOXZ74+ebGE/aP8RAK4/pjsOvjdr1OQ59BXJZd2eEqC1Y5cEM=,iv:Vvgd0bdrpnPEBE4XHKzf5+mREywDqk4qIzBpdxxBbxk=,tag:CMX9ZuMXo8EUboMN2ATNFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
