apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: arr
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name:  arr-pod
        image: linuxserver/sonarr
        ports:
        - containerPort: 7878
          name: http
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-pvc
