apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: db
spec:
  storageClassName: nfs-k8s
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
