apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: db
spec:
  selector:
    app: redis-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
