apiVersion: v1
kind: Service
metadata:
  name: victorialogs-svc
  namespace: victoria
spec:
  selector:
    app: 
  type: 
  ports:
  - name: 
    protocol: 
    port: 80
    targetPort: 5000
    nodePort: 30001
---

