apiVersion: v1
kind: Service
metadata:
  namespace: logs
  name: victorialogs-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 9428
      protocol: TCP
      targetPort: http
  selector:
    app: victorialogs-deploy
